#!/usr/bin/env bash

emacs --batch --eval                          \
      "(progn                                 \
         (setq sentence-end-double-space nil) \
         (checkdoc-file \"${1}\"))"           \
      2>&1                                    \
    | grep -v "^Warning (emacs): $"
